// hotTabs.ts
export const hotTabs = [
  {
    isShow: true,
    component: "BilibiliHot",
    label: "📺 哔哩哔哩",
    name: "bilibili",
  },
  { isShow: true, component: "WeiBoHot", label: "🌟 微博", name: "weibo" },
  {
    isShow: true,
    component: "DouYinHot",
    label: "🎵 抖音",
    name: "douyin",
    content: "抖音内容",
  },
  {
    isShow: true,
    component: "",
    label: "📕 小红书",
    name: "xiaohongshu",
    content: "小红书内容",
  },
  {
    isShow: true,
    component: "",
    label: "🧠 知乎",
    name: "zhihu",
    content: "知乎内容",
  },
  {
    isShow: true,
    component: "",
    label: "🧬 36氪",
    name: "36kr",
    content: "36氪内容",
  },
  {
    isShow: true,
    component: "",
    label: "🔍 百度",
    name: "baidu",
    content: "百度内容",
  },
  {
    isShow: false,
    component: "",
    label: "🔥 少数派",
    name: "sspai",
    content: "少数派内容",
  },
  {
    isShow: false,
    component: "",
    label: "📰 IT之家",
    name: "ithome",
    content: "IT之家内容",
  },
  {
    isShow: false,
    component: "",
    label: "🧾 澎湃新闻",
    name: "thepaper",
    content: "澎湃新闻内容",
  },
  {
    isShow: false,
    component: "",
    label: "🗞️ 今日头条",
    name: "toutiao",
    content: "今日头条内容",
  },
  {
    isShow: false,
    component: "",
    label: "💬 百度贴吧",
    name: "tieba",
    content: "百度贴吧内容",
  },
  {
    isShow: false,
    component: "",
    label: "💰 稀土掘金",
    name: "juejin",
    content: "稀土掘金内容",
  },
  {
    isShow: false,
    component: "",
    label: "🗞 腾讯新闻",
    name: "tencent",
    content: "腾讯新闻内容",
  },
  {
    isShow: false,
    component: "",
    label: "🎬 豆瓣电影",
    name: "douban",
    content: "豆瓣电影内容",
  },
  {
    isShow: false,
    component: "",
    label: "🎮 原神",
    name: "genshin",
    content: "原神内容",
  },
  {
    isShow: false,
    component: "",
    label: "🚄 星穹铁道",
    name: "starrail",
    content: "星穹铁道内容",
  },
  {
    isShow: false,
    component: "",
    label: "🏆 LOL",
    name: "lol",
    content: "LOL内容",
  },
  {
    isShow: false,
    component: "",
    label: "🗞 网易新闻",
    name: "netease",
    content: "网易新闻内容",
  },
  {
    isShow: false,
    component: "",
    label: "📚 微信读书",
    name: "wxread",
    content: "微信读书内容",
  },
  {
    isShow: false,
    component: "",
    label: "💬 豆瓣小组",
    name: "dougroup",
    content: "豆瓣小组内容",
  },
  {
    isShow: false,
    component: "",
    label: "🧠 NGA",
    name: "nga",
    content: "NGA内容",
  },
  {
    isShow: false,
    component: "",
    label: "💡 HelloGitHub",
    name: "hellogithub",
    content: "HelloGitHub内容",
  },
  {
    isShow: false,
    component: "",
    label: "📖 简书",
    name: "jianshu",
    content: "简书内容",
  },
  {
    isShow: false,
    component: "",
    label: "🧠 知乎日报",
    name: "zhihudaily",
    content: "知乎日报内容",
  },
];
